name: Validate with hassfest

on:
  push:
    tags:
      - '*'

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v3"
        - uses: "home-assistant/actions/hassfest@master"
